ibexa:
    system:
        admin_group:
            fieldtypes:
                ezrichtext:
                    custom_tags: [factbox, call_to_action]
                    toolbar:
                        ezadd:
                            buttons:
                                factbox:
                                    priority: 10
                                call_to_action:
                                    priority: 10

ibexa_fieldtype_richtext:
    custom_tags:
        factbox:
            template: '@ibexadesign/fields/ezrichtext/custom_tags/factbox.html.twig'
            icon: '/bundles/ibexaicons/img/all-icons.svg#about'
            attributes:
                title:
                    type: 'string'
        call_to_action:
            template: '@ibexadesign/fields/ezrichtext/custom_tags/call_to_action.html.twig'
            icon: '/bundles/ibexaicons/img/all-icons.svg#button'
            attributes:
                style:
                    type: 'choice'
                    default_value: 'primary'
                    required: true
                    choices: ['primary', 'secondary']
