default:
    image: registry.gitlab.com/ibexa-sa/accelerator:installer
    services:
        - name: mysql:8.0
          alias: mysql

variables:
    MYSQL_DATABASE: prototype
    MYSQL_ROOT_PASSWORD: ibexa

    DATABASE_USER: root
    DATABASE_HOST: mysql
    DATABASE_PASSWORD: $MYSQL_ROOT_PASSWORD
    DATABASE_NAME: $MYSQL_DATABASE

    # Following variables are configured via Gitlab API on project creation:
    # CLOUD_PROJECT_ID, CLOUD_REGION

    # Following variables are configured globally for the whole Instances sub-group
    # PROTOTYPE_INSTALLER_VERSION, IBEXA_SATIS_USERNAME, IBEXA_SATIS_TOKEN, GITLAB_TOKEN

    # Platform.sh CLI client looks for this env variable. If present no additional authentication is needed.
    PLATFORMSH_CLI_TOKEN: $PLATFORM_SH_API_TOKEN

.devops: &devops |
    set -e

    [[ $TRACE -eq 1 ]] && set -x

    # Configure SSH
    ssh-keyscan -H git.$CLOUD_REGION >> ~/.ssh/known_hosts
    ssh-keyscan -H ssh.$CLOUD_REGION >> ~/.ssh/known_hosts

    # Configure Composer
    composer config --global http-basic.updates.ibexa.co $IBEXA_SATIS_USERNAME $IBEXA_SATIS_TOKEN
    composer config --global gitlab-token.gitlab.com ${GITLAB_TOKEN}

    # Install Ibexa Prototype Installer
    curl -o /usr/local/bin/ibexa-prototype-installer -H "PRIVATE-TOKEN: $GITLAB_TOKEN" https://gitlab.com/api/v4/projects/17683500/packages/generic/ibexa-prototype-installer/${PROTOTYPE_INSTALLER_VERSION}/ibexa-prototype-installer.phar
    chmod +x /usr/local/bin/ibexa-prototype-installer

    function installer() {
        # Use Ibexa Prototype Installer to create project
        /usr/local/bin/ibexa-prototype-installer create-project installer-config.json ./project -t 1200

        # Move project files to the main repository directory
        rm -rf ./project/.git .gitlab-ci.yml
        find project -mindepth 1 -maxdepth 1 -exec mv {} . \;

        # Add all files and commit
        export CI_PUSH_URL=$(echo "$CI_REPOSITORY_URL" | sed -e "s|\(https://\)[^@]*|\1$USER_TOKEN:$PUSH_TOKEN|")
        git add .
        git add composer.lock
        git commit -m 'Installer commit'
        git push $CI_PUSH_URL HEAD:$CI_COMMIT_BRANCH
    }

    function deploy() {
        # Configure P.sh and push project files
        ~/.platformsh/bin/platform project:set-remote $CLOUD_PROJECT_ID -y
        mysqldump -h mysql -u root -pibexa prototype > dump.sql
        ~/.platformsh/bin/platform env:push --target=master -f -y
        ~/.platformsh/bin/platform sql --environment=master < dump.sql -y
        ~/.platformsh/bin/platform mount:upload --environment=master --source=public/var --mount=public/var -y

        # Clean-up P.sh instance and reindex
        echo "flushall" | ~/.platformsh/bin/platform service:redis-cli --environment=master -y
        echo "php bin/console c:c && php bin/console ibexa:reindex && php bin/console ibexa:graphql:generate-schema && php bin/console c:c" | ~/.platformsh/bin/platform ssh --environment=master -y
    }

before_script:
    - *devops

installer:
    stage: build
    script:
        - installer
        - deploy
stages:
    - build
