#index:
#    path: /
#    controller: App\Controller\DefaultController::index

ibexa.corporate_account.customer_portal.products.list:
  path: /customer-portal/products/list
  defaults:
    _controller: 'App\CustomerPortal\Controller\ProductController::listAction'